@echo off
echo Running startup script...

echo Starting Backend...
start cmd /k "uv sync && cd backend && uv run uvicorn app:app --reload --host 0.0.0.0 --port 8000"

echo Starting Frontend...
start cmd /k "cd frontend && npm install && npm run dev"